export const GET_ALL_SECONDARY_CARDS_DATA_REQUEST =
  "GET_ALL_SECONDARY_CARDS_DATA_REQUEST";
export const GET_ALL_SECONDARY_CARDS_DATA_SUCCESS =
  "GET_ALL_SECONDARY_CARDS_DATA_SUCCESS";
export const GET_ALL_SECONDARY_CARDS_DATA_FAILURE =
  "GET_ALL_SECONDARY_CARDS_DATA_FAILURE";
export const GET_SECONDARY_CARDS_DATA_REQUEST =
  "GET_SECONDARY_CARDS_DATA_REQUEST";
export const GET_SECONDARY_CARDS_DATA_SUCCESS =
  "GET_SECONDARY_CARDS_DATA_SUCCESS";
export const GET_SECONDARY_CARDS_DATA_FAILURE =
  "GET_SECONDARY_CARDS_DATA_FAILURE";
