export const GET_SECONDARY_CARDS_DATA_REQUEST =
  "GET_SECONDARY_CARDS_DATA_REQUEST";
export const GET_SECONDARY_CARDS_DATA_SUCCESS =
  "GET_SECONDARY_CARDS_DATA_SUCCESS";
export const GET_SECONDARY_CARDS_DATA_FAILURE =
  "GET_SECONDARY_CARDS_DATA_FAILURE";
export const GET_FILTER_BY_DATE_REQUEST = "GET_FILTER_BY_DATE_REQUEST";
export const GET_FILTER_BY_DATE_SUCCESS = "GET_FILTER_BY_DATE_SUCCESS";
export const GET_FILTER_BY_DATE_FAILURE = "GET_FILTER_BY_DATE_FAILURE";
export const GET_FILTER_BY_TYPE_REQUEST = "GET_FILTER_BY_TYPE_REQUEST";
export const GET_FILTER_BY_TYPE_SUCCESS = "GET_FILTER_BY_TYPE_SUCCESS";
export const GET_FILTER_BY_TYPE_FAILURE = "GET_FILTER_BY_TYPE_FAILURE";
export const GET_SEARCH_BY_TITLE_REQUEST = "GET_SEARCH_BY_TITLE_REQUEST";
export const GET_SEARCH_BY_TITLE_SUCCESS = "GET_SEARCH_BY_TITLE_SUCCESS";
export const GET_SEARCH_BY_TITLE_FAILURE = "GET_SEARCH_BY_TITLE_FAILURE";
